### PR TITLE
feat(ids): add TypeScript definitions

### PR DESCRIPTION
**Pull request by nikeee**

### CODE REVIEW

**Comment by nikku** [comment]
The seed must be an array of two or three numbers: Cf. https://www.npmjs.com/package/hat#var-rack--hatrackbits128-base16-expandby.

**Comment by nikku** [comment]
Not sure if it is worth adding that to the definitions?

**Comment by nikeee** [comment]
> Not sure if it is worth adding that to the definitions?

Actually, it would be easier to just port the whole thing to TypeScript and use the compiled `.js` or `.d.ts` file. But I don't want to change your toolchain and I don't want to induce large changes.

Additionally, we currently have the task at a university course to take parts of diagram.js and rewrite some of it in TypeScript. The intention behind all these type definition additions is to make it easier to do so.

> The seed must be an array of two or three numbers

I changed the type of seed from `number[]` to `[number, number] | [number, number, number]`, so only arrays (or "tuples" in this case) of length 2 or 3 can be passed.

**Comment by nikku** [comment]
> Additionally, we currently have the task at a university course to take parts of diagram.js and rewrite some of it in TypeScript. The intention behind all these type definition additions is to make it easier to do so.

You could start with an extension such as diagram-js origin (or some other small plug-in). As long as you generate ES modules everything should be fine for end-users.

**Pull request merged**
